name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build APK
        run: |
          chmod +x gradlew
         ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: APK-BUILDER-RESULT
          path: app/build/outputs/apk/debug/*.apk
